baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Reed Schimmel"
theme: "./.."
relativeURLs: true

# googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/profile.png"
  description: "Reed Schimmel - Automated Trading Engineer; portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Reed Schimmel"
  namecolor: ffc107
  profession: "Automated Trading Engineer"
  github: "https://github.com/Reed-Schimmel"
  # gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/reedschimmel/"
  # twitter: "https://twitter.com/"
  # instagram: "https://instagram.com/"
  # facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: true
  descripe_l1_person: "Hi, I'm Profile, This site is still under development."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: Python
      percentage: 90
    - name: QuantConnect
      percentage: 85
    - name: PineScript
      percentage: 80
    - name: Kubernetes
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "Spiffy-Composites"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Co-Founder"
      startdate: Oct 2019
      enddate: Jun 2020
      featuredpoints:
        - point: Built MVP requirements doc by conducting customer discovery interviews.
        - point: Developed crossplatform iOS/Android/web frontend with Expo SDK.
        - point: CI / CD with BitBucket Pipelines to automated versioning, building, testing and app store deployment.
        - point: Backend composite rendering with Google Cloud Functions and Puppeteer.
    - company: "PayIt"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software Engineer Intern"
      startdate: May 2019
      enddate: Aug 2019
      featuredpoints:
        - point: Reduced remittance issues by eliminating network race condition in Java web-API on Kubernetes.
        - point: Helped increase annual recurring revenue by deploying iOS and Android mobile app for oncoming client.
        - point: Increased mobile app stability by eliminating fatal react-native- push-notification bug affecting 100% of Android client apps.
        - point: Accelerated marketing capacity by developing a service to target potential customers based on previous purchases.
    - company: "KingFit"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Chief Technology Officer"
      startdate: May 2017
      enddate: Apr 2018
      featuredpoints:
        - point: Developed iOS and Android app in React Native to deliver diabetes education video content.
        - point: Published and managed App Store listing with Google Play and iTunes Connect.
        - point: Enabled product monetization by designing and developing Expo compatible video analytics system.
    - company: "Parkmo"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Founder"
      startdate: Dec 2015
      enddate: May 2017
      featuredpoints:
        - point: Decreased student commute by up to 20 minutes, by informing them of parking availability via mobile app.
        - point: Eliminated printed parking passes, saving KU $16,000/yr in printing, by using license plate recognition technology.
        - point: Greatly reduced parking theft by replacing two-hour, manual patrols with constant automated monitoring.
        - point: Awarded $1,200 from Koch Innovation Challenge 2015 with parking enforcement demo.
        - point: Placed 3rd out of 62 teams in SNVC 2016, winning $2,000 of seed funding, with business plan and product prototype.

  # Education
  disable_education: true
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "contact-reed.ofkd5@aleeas.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
